### ISSUE TITLE
When zod specifies z.date(), type is converted to date-time rather than date

### ISSUE THREAD

**Issue by matthew-kaye** [StefanTerdell/zod-to-json-schema#109]
Steps to reproduce:

- use z.date() in zod rather than z.string().datetime()
- Run the conversion
- Observe type as date-time rather than date

**Comment by StefanTerdell** [comment]
Hello @matthew-kaye, thanks for opening an issue.

The behavior you describe makes sense to me. z.date() represents the JS Date class, which by default is serialized to JSON as a date-time string, thus matching z.string().datetime().

Feel free to reopen the issue if you don't agree!

**Comment by matthew-kaye** [comment]
> Hello @matthew-kaye, thanks for opening an issue.
> 
> The behavior you describe makes sense to me. z.date() represents the JS Date class, which by default is serialized to JSON as a date-time string, thus matching z.string().datetime().
> 
> Feel free to reopen the issue if you don't agree!

I'm not sure I do agree actually sorry 😅 Since a zod schema for `z.date()` would allow a data field like "2024-01-01" but a JSON schema requiring a date-time would not. It seems normal to me to expect that data which would pass the zod schema would also be accepted by the JSON schema generated from it

<img width="570" alt="image" src="https://github.com/StefanTerdell/zod-to-json-schema/assets/49241458/ffc38f82-1670-4d35-ad64-2812fa924e9b">
