### ISSUE TITLE
Add title property of JSON Schema from zod definitions

### ISSUE THREAD

**Issue by flower-of-the-bridges** [StefanTerdell/zod-to-json-schema#121]
Hi

I would like to generate a JSON schema like the following:

```json
{
  "type": "object",
  "title": "My Json Schema Title",
  "required": ["someProperty"],
  "properties": {
    "someProperty": {
      "type": "string"
    },
  },
  "additionalProperties": false
}
``` 

Is there a way to achieve a JSON Schema like that using `zod` definitions? 

If not, what could be a possible feature to add to the library?

Thanks

**Comment by StefanTerdell** [comment]
I could add an option for it, probably in the coming week :)

**Comment by flower-of-the-bridges** [comment]
@StefanTerdell great, thanks!! If you need help, I'd be happy to contribute

**Comment by StefanTerdell** [comment]
@flower-of-the-bridges Bit late to the party, but you can now use the "name" and "nameStrategy" = "title" to add "title" to the root schema
