### ISSUE TITLE
The `coerce` config is lost during conversion

### ISSUE THREAD

**Issue by Adeniyii** [StefanTerdell/zod-to-json-schema#131]
e.g `z.coerce.number()` returns just a number type without the coercion meta.

**Comment by StefanTerdell** [comment]
As far as I'm aware there is no way to represent coercion in JSON schema.

**Comment by Adeniyii** [comment]
Closed as this was explained in more detail [here](https://github.com/StefanTerdell/zod-to-json-schema/issues/130)
