### ISSUE TITLE
Cleaner way of turning zod objects to json schema with Typescript support

### ISSUE THREAD

**Issue by volkandkaya** [StefanTerdell/zod-to-json-schema#134]
```js
export const zodObjectToJsonSchema = <T extends z.ZodObject<any>>(
  zSchema: T
) => {
  const schema = zodToJsonSchema(zSchema, {
    name: 'schemaName',
  });

  if (!schema.definitions?.schemaName) {
    throw new Error('Schema name not found');
  }

  return schema.definitions['schemaName'] as JSONSchema7;
};
```

Instead of getting JSONSchema7 I get JsonSchema7Type. Fastify requires JSONSchema7.

Also somehow schema.definitions can be undefined even if I pass in

```
const EmailSchema = z.string().email("Invalid email").min(5, "Too short");
```

**Comment by StefanTerdell** [comment]
@volkandkaya Hi! Thanks for opening an issuel. I'm going to close this one as it looks out of scope. Feel free to tag me in a reply if you disagree.

> Instead of getting JSONSchema7 I get JsonSchema7Type. Fastify requires JSONSchema7.

I'm looking at reviewing the output types in v4, you can safely cast it in the meantime.

> Also somehow schema.definitions can be undefined even if I pass in [...]

Schema structure is not preserved. That's a whole other level of complexity and has never been a goal of this project.

**Comment by volkandkaya** [comment]
https://jsonforms.io/api/core/interfaces/jsonschema7.html seems to be the "correct" type and follows Fastify typing. Would it break things if you changed to that in v3?

"Schema structure is not preserved" this would be amazing, but I can understand the complexity.
