### ISSUE TITLE
Uint8Array support

### ISSUE THREAD

**Issue by ryan0x44** [StefanTerdell/zod-to-json-schema#141]
Currently if I define `z.instanceof(Uint8Array)` I get an empty schema.

It be great if one of two things happened:

1. zod-to-json-schema offered some kind of escape-hatch/hooks system where I could handle edge cases like this using my own schema encoder

OR

2. zod-to-json-schema generated the following schema for storing binary data:

```
{
	"type": "string",
	"contentEncoding": "base64",
	"contentMediaType": "application/octet-stream"
}
```

per https://json-schema.org/understanding-json-schema/reference/non_json_data

**Comment by StefanTerdell** [comment]
1. Try the override option
2. The correct schema would depend on the JSON serialization technique used. There's prior art for this with Map and Set, but those cases are a little more cut and dry.
