### ISSUE TITLE
exclusiveMinimum and exclusiveMaximum should be boolean, not number

### ISSUE THREAD

**Issue by Newbie012** [StefanTerdell/zod-to-json-schema#15]
According to https://json-schema.org/understanding-json-schema/reference/numeric.html

>In JSON Schema Draft 4, exclusiveMinimum and exclusiveMaximum work differently. There they are boolean values, that indicate whether minimum and maximum are exclusive of the value

While trying to match its return type with `@typescript-eslint/utils`.`RuleMetaData.schema`, I'm getting:

```typescript
Type '{ $schema: "http://json-schema.org/draft-07/schema#"; } & JsonSchema7Type' is not assignable to type 'JSONSchema4 | readonly JSONSchema4[]'.
  Type '{ $schema: "http://json-schema.org/draft-07/schema#"; } & JsonSchema7NumberType & { default?: any; description?: string | undefined; }' is not assignable to type 'JSONSchema4 | readonly JSONSchema4[]'.
    Type '{ $schema: "http://json-schema.org/draft-07/schema#"; } & JsonSchema7NumberType & { default?: any; description?: string | undefined; }' is not assignable to type 'JSONSchema4'.
      Types of property 'exclusiveMaximum' are incompatible.
        Type 'number | undefined' is not assignable to type 'boolean | undefined'.
          Type 'number' is not assignable to type 'boolean | undefined'.ts(2322)
```

**Comment by StefanTerdell** [comment]
In draft 7 (which is the default target) they are numbers. If you wish to target draft 4, try running it in openApi mode, it's closer.

**Comment by StefanTerdell** [comment]
@Newbie012 To clarify, check the last option here https://github.com/StefanTerdell/zod-to-json-schema#options-object

Be aware the typings for openApi-mode result is lacking
