### ISSUE TITLE
Is there any plan for implementing draft-04?

### ISSUE THREAD

**Issue by orekav** [StefanTerdell/zod-to-json-schema#155]
I am trying to use JSON Schema validator for AWS AppConfig, the issue is that it only accepts draft-04 [AWS Documentation](https://docs.aws.amazon.com/appconfig/latest/userguide/appconfig-creating-configuration-and-profile-validators.html#appconfig-creating-configuration-and-profile-validators-json-schema)

My current workaround is just to set an invalid `target`  as `ANY` 😢. When I do this, the property `$schema` dissapears.

**Comment by StefanTerdell** [comment]
Thanks for opening an issue!

Unfortunately there are no plans to support draft 4. The OpenAPI target is pretty close though, so you might have better luck with that, but bare in mind that this will likely be removed in the next major later OpenAPI versions support JSON Schema draft 2020.

Your best bet is probably to generate a modern version and then use some transformation tool to downgrade it.

Good luck!
