### ISSUE TITLE
BUG: A number with min value and optional defined  gives wrong type

### ISSUE THREAD

**Issue by bovandersteene** [StefanTerdell/zod-to-json-schema#156]
A number defined as following
```ts
 anOptionalNumber: z.number().min(0).nullish(),
```

Gives a anyOf output like this
```ts
"anOptionalNumber": {
      "anyOf": [
        {
          "type": "number",
          "minimum": 0
        },
        {
          "type": "null"
        }
      ]
    }
},
```

I should be  that it would look like
```ts
"anOptionalNumber": {
          "type": "number",
          "minimum": 0
},
```

**Comment by StefanTerdell** [comment]
Hello @bovandersteene! Thanks for opening an issue. I think you have misunderstood the role of `nullish` - it allows for either `null` or `undefined` so the output is correct. To produce your wanted output you should use `z.number().min(0).optional()`.
