### ISSUE TITLE
Bug: `z.string().nullable()` converts to `any`

### ISSUE THREAD

**Issue by chriskuech** [StefanTerdell/zod-to-json-schema#16]
# Repro
1. Define one of the types below
  ```
  z.string().nullable()
  z.union([z.string(), z.null()])
  ```
  as well as a control case
  ```
  z.number().nullable()
  ```
2. Convert to JSON schema.

# Expected
Similar to `z.number().nullable()`, the type should have been `string | null`.

# Observed
The type is `any`.

**Comment by StefanTerdell** [comment]
@chriskuech Cant reproduce. Added a test, let me know what you would change. [[ Link ]](https://github.com/StefanTerdell/zod-to-json-schema/blob/master/test/parseDef.test.ts#L159-L167)

**Comment by chriskuech** [comment]
I just realized this bug does not make sense. We have zod -> json schema (openapi) -> typescript client. `any` is a typescript concept and must be occurring in the typescript client.

**Comment by StefanTerdell** [comment]
Ah, thought you were describing an `any`-like JSON schema, like `{}` or `true`
