### ISSUE TITLE
ZodDiscriminatedUnionDef 

### ISSUE THREAD

**Issue by MirZa-LB** [StefanTerdell/zod-to-json-schema#32]
> tsc -b

node_modules/zod-to-json-schema/src/parsers/union.d.ts:22:58 - error TS2707: Generic type 'ZodDiscriminatedUnionDef<Discriminator, Options>' requires between 1 and 2 type arguments.

22 export declare function parseUnionDef(def: ZodUnionDef | ZodDiscriminatedUnionDef<any, any, any>, refs: References): JsonSchema7PrimitiveUnionType | JsonSchema7AnyOfType | undefined;
                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by StefanTerdell** [comment]
Duplicate of #31
