### ISSUE TITLE
Support for JSONSchema4 types were dropped in 3.20.0

### ISSUE THREAD

**Issue by Newbie012** [StefanTerdell/zod-to-json-schema#35]
It seems like since 3.20.0, even if you specify `openApi3` instead of `jsonSchema7`, the return type is still `JsonSchema7Type`

![image](https://user-images.githubusercontent.com/10504365/209951090-e7e90b7a-1d41-47c4-b7c3-c85da92044fa.png)

Since [ESLint's `schema` option](https://github.com/StefanTerdell/zod-to-json-schema/commit/9a4a59a2a30e2a28a73b7a7db70cdd5747ec5d10) supports only JSONSchema4, I'm unable to upgrade to draft-07 which leads to the following type error:

```
Type 'JsonSchema7Type & { $schema?: string | undefined; definitions?: { [key: string]: JSONSchema7Type; } | undefined; }' is not assignable to type 'JSONSchema4 | readonly JSONSchema4[]'.
```

![image](https://user-images.githubusercontent.com/10504365/209951135-befd5ad3-6ab6-4c27-a799-732961207def.png)

This is the change:
```diff
- function zodToJsonSchema<
-   Name extends string | undefined = undefined,
-   Strategy extends "root" | "relative" | "none" | undefined = undefined,
-   BasePath extends string[] | undefined = undefined,
-   DefinitionPath extends "definitions" | "$defs" = "definitions",
-   Target extends "jsonSchema7" | "openApi3" | undefined = undefined,
-   Definitions extends Record<string, ZodSchema<any>> | undefined = undefined
- >(
-   schema: ZodSchema<any>,
-   options?: {
-     name?: Name;
-     $refStrategy?: Strategy;
-     basePath?: BasePath;
-     effectStrategy?: EffectStrategy;
-     definitionPath?: DefinitionPath;
-     target?: Target;
-     strictUnions?: boolean;
-     definitions?: Definitions;
-   }
- ): Target extends "openApi3"
-   ? Name extends string
-     ? BasePath extends string[]
-       ? {
-           $ref: string;
-         } & Record<DefinitionPath, Record<Name | keyof Definitions, object>>
-       : Strategy extends "relative"
-       ? {
-           $ref: `0/${DefinitionPath}/${Name}`;
-         } & Record<DefinitionPath, Record<Name | keyof Definitions, object>>
-       : {
-           $ref: `#/${DefinitionPath}/${Name}`;
-         } & Record<DefinitionPath, Record<Name | keyof Definitions, object>>
-     : object
-   : Name extends string
-   ? BasePath extends string[]
-     ? {
-         $schema: "http://json-schema.org/draft-07/schema#";
-         $ref: string;
-       } & Record<
-         DefinitionPath,
-         Record<Name | keyof Definitions, JsonSchema7Type>
-       >
-     : Strategy extends "relative"
-     ? {
-         $schema: "http://json-schema.org/draft-07/schema#";
-         $ref: `0/${DefinitionPath}/${Name}`;
-       } & Record<
-         DefinitionPath,
-         Record<Name | keyof Definitions, JsonSchema7Type>
-       >
-     : {
-         $schema: "http://json-schema.org/draft-07/schema#";
-         $ref: `#/${DefinitionPath}/${Name}`;
-       } & Record<
-         DefinitionPath,
-         Record<Name | keyof Definitions, JsonSchema7Type>
-       >
-   : Definitions extends undefined
-   ? { $schema: "http://json-schema.org/draft-07/schema#" } & JsonSchema7Type
-   : { $schema: "http://json-schema.org/draft-07/schema#" } & JsonSchema7Type &
-       Record<DefinitionPath, Record<keyof Definitions, JsonSchema7Type>>;
```

**Comment by Newbie012** [comment]
Correction - It actually returns draft-07 in runtime, leading to failing tests ([see here](https://github.com/ts-safeql/safeql/actions/runs/3800584881/jobs/6464205437)).

**Comment by StefanTerdell** [comment]
Damn - sorry about that. I'll look into it. As you can see from the change the external type api was a complete mess and needed refactoring but looks like I cut too deep. The tests failing seem odd to me though - this should have caught it: https://github.com/StefanTerdell/zod-to-json-schema/blob/master/test/openApiMode.test.ts

**Comment by StefanTerdell** [comment]
Could this be the culprit? https://github.com/ts-safeql/safeql/pull/106/files#diff-3396d504ac06e253b2bbc2a9d078c8878114bb2c48df838a219f585e9b196699R477

**Comment by StefanTerdell** [comment]
If it is, I'd suggest type coercing for now; I don't have a lot of spare time at the moment.

**Comment by Newbie012** [comment]
Oh... that's definitely my fault there 😅 I probably left it when I did my checks. In any case, I casted it to an `object` and it seems good enough. Thanks for pointing that out!

**Comment by StefanTerdell** [comment]
Mind having a look at #36? Should fix this issue.
