### ISSUE TITLE
error: module not found `parseDef`

### ISSUE THREAD

**Issue by navtoj** [StefanTerdell/zod-to-json-schema#39]
| Platform | Version |
| :- | :- |
| Deno | [3.20.0](https://deno.land/x/zod_to_json_schema@3.20.0) |
```ts
// deno run --allow-all test.ts
import { z } from 'https://deno.land/x/zod@v3.20.2/index.ts';

// import { zodToJsonSchema } from 'npm:zod-to-json-schema@latest';
import { zodToJsonSchema } from 'https://deno.land/x/zod_to_json_schema@3.20.0/zodToJsonSchema.ts';

const schema = z.string();

const json = zodToJsonSchema(schema);

console.log(json);
```

When I run the code shown above, I get the below error.

```console
error: Module not found "https://deno.land/x/zod_to_json_schema@3.19.0/parseDef".
    at https://deno.land/x/zod_to_json_schema@3.19.0/zodToJsonSchema.ts:2:43
```

However, when i use `npm:zod-to-json-schema@latest`, I get the correct output shown below.
```js
{ type: "string", "$schema": "http://json-schema.org/draft-07/schema#" }
```

(p.s. might be similar to #33)

**Comment by StefanTerdell** [comment]
I will admit I've no idea what I'm doing when it comes to cutting Deno-releases, but it looks like the latest tag hasn't been picked up. If anyone is interested in helping out with a decent pipeline for this please let me know

**Comment by StefanTerdell** [comment]
@navtoj Could you confirm if the latest release solved this? https://deno.land/x/zod_to_json_schema@3.20.3

**Comment by navtoj** [comment]
@StefanTerdell Still getting the same error in `3.20.3`.

```shell
error: Module not found "https://deno.land/x/zod_to_json_schema@3.20.3/parseDef".
    at https://deno.land/x/zod_to_json_schema@3.20.3/zodToJsonSchema.ts:4:43
```

**Comment by StefanTerdell** [comment]
Looks like deno wants a .ts at the end of imports, like
`import { JsonSchema7Type, parseDef } from "./parseDef.ts";`, but then node won't build instead. There really needs to be some time devoted into setting up a proper build pipeline for this package. Fow now, I'll continue to support those who are able to use the package successfully.

Would be happy to accept PRs addressing this though.

**Comment by savy-91** [comment]
I do not have time to contribute back to this repo at the moment, but I managed to "denoify" this repo building a distribution that works on Deno. You can find my fork here if you want to see how to do it @StefanTerdell : https://github.com/savy-91/zod-to-json-schema

If you want to use it in your project @navtoj you can just

```
import zodToJsonSchema from 'https://raw.githubusercontent.com/savy-91/zod-to-json-schema/3.20.4/deno_dist/zodToJsonSchema.ts';
```

**Comment by StefanTerdell** [comment]
@savy-91 I started tinkering with a Deno build but realized I don't really care enough 😅. However, I just released a new version. If you update your fork based on that I will link it in the documentation.

If you want to create a PR with a build script for Deno that would be awesome as well of course.

**Comment by StefanTerdell** [comment]
AFAIK Deno supports NPM now, so I consider this a non-issue.
