### ISSUE TITLE
Order of optional and nullable matters

### ISSUE THREAD

**Issue by urugator** [StefanTerdell/zod-to-json-schema#42]
Hi, thank you for the library. The shape of the `openApi3` schema depends on the application order of `.nullable` and `.optional`. I assume both versions are functionally identical. Unfortunatelly `nullish` produces the less favorable version :(  Is this expected?
```javascript
z.object({
  nullableOptional: z.number().nullable().optional(),
  optionalNullable: z.number().optional().nullable(),
  nullish: z.number().nullish(),
})
```
=>
```json
{
  "nullableOptional": {
    "type": "number",
    "nullable": true
  },
  "optionalNullable": {
    "anyOf": [
      {
        "not": {}
      },
      {
        "type": "number"
      }
    ],
    "nullable": true
  },
  "nullish": {
    "anyOf": [
      {
        "not": {}
      },
      {
        "type": "number"
      }
    ],
    "nullable": true
  }
}
```

**Comment by urugator** [comment]
If I read the sources correctly, parsers like nullable/union try to simplify the output whenever the inner types are primitive, but the inner type in this case is optional and the algo doesn't try to look further at it's inner type...

OT: any reason why this check:
https://github.com/StefanTerdell/zod-to-json-schema/blob/cd6fac76a5ffafee067635c8ebf069ac2daa7395/src/parsers/nullable.ts#L20-L22
doesn't use (`in primitiveMappings`) like here:
https://github.com/StefanTerdell/zod-to-json-schema/blob/master/src/parsers/union.ts#L51
??

**Comment by urugator** [comment]
The application order in case of `nullish` was actually already fixed in `zod`, but it's not released yet:
https://github.com/colinhacks/zod/commit/0c0e49517e4dfa666017d7fd863c4c18c2bf7987

**Comment by StefanTerdell** [comment]
Closing this since Zod is a peer dependency and this can be fixed by just bumping it.
