### ISSUE TITLE
Deno instructions

### ISSUE THREAD

**Issue by Hexagon** [StefanTerdell/zod-to-json-schema#47]
👋 

I notice that this module is published to deno.land/x, but i can not figure out how to get it working. Have fiddled with import map and npm:-specifiers to no avail.

Any pointers?

**Comment by cdaringe** [comment]
the issue is closed, but i don't see the solve. can you elaborate?

**Comment by Hexagon** [comment]
Finally got it working using `import { zodToJsonSchema } from "npm:zod-to-json-schema@3.20.4"`. So the issue isn't really resolved i guess.
