### ISSUE TITLE
Any way to add style: deepObject? 

### ISSUE THREAD

**Issue by abhishek-butola** [StefanTerdell/zod-to-json-schema#49]
```- schema:
            type: object
            properties:
              page:
                type: number
                minimum: 0
              limit:
                type: number
                maximum: 100
            additionalProperties: false
          in: query
          name: pagination
          required: true
          style: deepObject # <----------```

**Comment by StefanTerdell** [comment]
@abhishek-butola Can you provide more context? When and why would you want this?

**Comment by abhishek-butola** [comment]
@StefanTerdell I am having an issue passing json object as query string.
https://stackoverflow.com/questions/75885273/swagger-is-unable-to-make-request-with-query-string-having-json

**Comment by StefanTerdell** [comment]
This is not related to zodToJsonSchema, as it only produces what goes into the "schema" keyword in your example.

There are higher level projects that may be more suitable, such as https://github.com/asteasolutions/zod-to-openapi.
