### ISSUE TITLE
Add support for "deprecated" keyword

### ISSUE THREAD

**Issue by william-will-angi** [StefanTerdell/zod-to-json-schema#53]
It would be good to be able to mark certain properties as deprecated within the json-schema.

https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.3

Let me know if there is anything I can do to help with this and I will be happy to put together a PR.

**Comment by StefanTerdell** [comment]
Yes, but that would require there to be a matching flag in the original Zod schema, so I'd take this feature suggestion over there for now. Closing in the meantime.
