### ISSUE TITLE
z.set should enforce items uniqueness

### ISSUE THREAD

**Issue by zygisau** [StefanTerdell/zod-to-json-schema#54]
One of the set's valuable points is its items' uniqueness. I suggest interpreting z.set as unique items array.

For example, let's say I have a schema for filter validation. It has `status` property which could be an array of possible statuses.

```typescript
export const statuses = z.enum([
	"draft",
	"submitted",
	"approved",
	"rejected",
	"archived",
]);

export const form = z
	.object({
		status: z.set(statuses),
	})
	.partial();
```

Since this is used in filtering, I would expect to be able to filter items by multiple statuses. The following snippet shows how I would expect schema to look like:

```jsonc
{
  // ...
  "status": {
    "type": "array",
    "uniqueItems": true, // <- this property is not present in the current output
    "items": {
      "type": "string",
      "enum": [
          "draft",
          "submitted",
          "approved",
          "rejected",
          "archived"
      ]
    }
  }
}
```

Let me know what You think about this feature.

**Comment by StefanTerdell** [comment]
Added in 3.20.5
