### ISSUE TITLE
Don't add definitions in the schema if they're not used

### ISSUE THREAD

**Issue by Janpot** [StefanTerdell/zod-to-json-schema#58]
Considering the following snippet:

```tsx
import * as z from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

const definition1 = z.string();

const definition2 = z.number();

const mySchema = z.object({
  prop: definition2,
});

const jsonSchema = zodToJsonSchema(mySchema, {
  definitions: {
    definition1,
    definition2,
  },
});

console.log(JSON.stringify(jsonSchema, null, 2));
```
This produces
```json
{
  "type": "object",
  "properties": {
    "prop": {
      "$ref": "#/definitions/definition2"
    }
  },
  "required": [
    "prop"
  ],
  "additionalProperties": false,
  "definitions": {
    "definition1": {
      "type": "string"
    },
    "definition2": {
      "type": "number"
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}
```

with a definition for `definition1`, even though it's not referenced anywhere. This is cumbersome in the scenario where I want to generate multiple schema's from zod types that may or may not use a common set of zod types.

**Comment by StefanTerdell** [comment]
I'm thinking this would probably make sense to accomplish beforehand with a preprocessing function. Definitions in JSON schemas could potentially be referenced without being used locally, so there's a hypothetical danger to ignoring user input to the API. If we were to pursue an implementation of this filter it should be opt-in.
