### ISSUE TITLE
Zod discriminatedUnion should generate oneOf

### ISSUE THREAD

**Issue by StratilJakub** [StefanTerdell/zod-to-json-schema#60]
Hi, first I want to thank you for your work on this library. I appreciate it.

In the Zod description of `discriminatedUnion`: https://github.com/colinhacks/zod#discriminated-unions
the condition logic is equal to description of `oneOf`: https://json-schema.org/understanding-json-schema/reference/combining.html#oneof

From my testing, both Zod's `union` and `discriminatedUnion` result in generation of `anyOf` JSON schema.

**Comment by StratilJakub** [comment]
I am working on MR.

**Comment by StefanTerdell** [comment]
Thanks, but a discriminated union should be fine with `anyOf`. `oneOf` is quite problematic, so unless you can provide a case for it with failing validation I am not likely to merge it.

**Comment by StefanTerdell** [comment]
Thanks, but a discriminated union should be fine with `anyOf`. `oneOf` is quite problematic, so unless you can provide a case for it with failing validation I am not likely to merge it.

**Comment by StratilJakub** [comment]
When you have the time, can you elaborate how is `oneOf` problematic?
From what I saw of the implementation it should be exactly same as for `union`, except generating `oneOf` instead of `anyOf` for non-primitive types?

I can't think of a specific invalid case right now. Right now I am using the generated schema for documentation and my intent was to make it 1-to-1 with previous AJV schema. So e.g. the documentation for an endpoint changes slightly from AJV version to Zod, which someone may consider breaking change, but I guess context wise it is same. :) 

Anyway I guess there is no real issue then, thanks for your reply.
