### ISSUE TITLE
TypeScript: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by NfNitLoop** [StefanTerdell/zod-to-json-schema#69]
Simple reproduction:

<img width="816" alt="Screenshot 2023-06-01 at 4 33 54 PM" src="https://github.com/StefanTerdell/zod-to-json-schema/assets/339075/a87539b8-e7d4-4b00-aefa-d90900c81bf9">

Gives this error both in VSCode and on the CLI:

```
> deno check example.ts
error: TS2589 [ERROR]: Type instantiation is excessively deep and possibly infinite.
const json = zodToJsonSchema(MyObject, "MyObject")
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If anyone has a workaround I'd appreciate it. I'm trying to propose using zod-to-json-schema and it's going to be a no-go if it doesn't type-check. 😬

**Comment by NfNitLoop** [comment]
Bah, figured it out.  This is basically an issue introduced by Deno's (lack of) dependency resolution.

`deno info example.ts` shows the problem:

```
file:///.../example.ts (463B)
├─┬ https://deno.land/x/zod@v3.21.4/mod.ts (28B)

…

└─┬ https://esm.sh/v124/zod-to-json-schema@3.21.1/ (233B)
  ├─┬ https://esm.sh/v124/zod-to-json-schema@3.21.1/index.d.ts (122B)
  │ └─┬ https://esm.sh/v124/zod-to-json-schema@3.21.1/src/zodToJsonSchema.d.ts (630B)
  │   ├─┬ https://esm.sh/v124/zod@3.21.4/index.d.ts (59B)
```

So I end up getting two different copies of the `zod` library. My guess is that TypeScript is having to walk down into each separate copy of Zod's quite complex types to make sure they're structurally equivalent and it's bailing at some point.

TypeScript probably has a shortcut when the types are literally equivalent that keeps it going down this rabbit hole.  If I update my imports to use the same versions of Zod, the error goes away:

```typescript
// Make sure we & z2js use the same Zod version, else types go wonky:
import { z } from "https://esm.sh/zod@v3.21.4";
import { zodToJsonSchema } from "https://esm.sh/v124/zod-to-json-schema@3.21.1/?deps=zod@3.21.4"
```

**Comment by lucacasonato** [comment]
Consider using `npm:` specifiers. Dependency resolution and de-dupe works as it does in Node there.

**Comment by vidz1979** [comment]
Thank you @NfNitLoop! Using esm.sh with deps specifier works very well!
