### ISSUE TITLE
TypeScript Union should be `oneOf` in JSON Schema

### ISSUE THREAD

**Issue by MunifTanjim** [StefanTerdell/zod-to-json-schema#7]
## Current Behavior

`z.union([z.number(), z.string()]` produces:

```json
{
  "anyOf": [
    {
      "type": "array",
      "items": {
        "type": "number",
      },
    },
    {
      "type": "array",
      "items": {
        "type": "string",
      },
    },
  ],
}
```

## Expected Behavior

It should produce `oneOf`.

**Comment by StefanTerdell** [comment]
Why? Please provide a problem case

**Comment by MunifTanjim** [comment]
Sorry about the noise. I misunderstood the problem I was having.

I was using https://github.com/drwpow/openapi-typescript and it converts `anyOf` as `Partial<number> & Partial<string>`. So the actual issue is caused by the `openapi-typescript` library.

**Comment by StefanTerdell** [comment]
# oneOf
`oneOf` is essentially useless and a pitfall for bad practices of schema building. I can't think of a single case where you wouldn't want to use a discriminated union instead. Not saying there aren't any, but... yaknow. If anyone comes across this in the future, consider the following:

## Zod
```typescript
const unionSchema = z.union([z.string(), z.string()])
```
With the above Zod schema, any string will pass validation.

## Current output
```json
{
  "anyOf": [
    {
      "type": "string"
    },
    {
      "type": "string"
    }
  ]
}
```
With the above JSON schema, any string will pass validation, just like the source Zod schema.

## Output with proposed change in issue
```json
{
  "oneOf": [
    {
      "type": "string"
    },
    {
      "type": "string"
    }
  ]
}
```
With the above JSON schema, ***no value will ever pass validation.*** The schema is "broken". 😿
