### ISSUE TITLE
Handling of differences between Zod and Json Schema

### ISSUE THREAD

**Issue by marcesengel** [StefanTerdell/zod-to-json-schema#73]
Hi!

When looking through the [json schema specs on emails](https://json-schema.org/understanding-json-schema/reference/string.html#email-addresses) and [how zod handles them](https://github.com/colinhacks/zod/pull/2157) I realised there's a fundamental difference: while the json schema spec uses RFC 5321 for `email` and RFC 6531 for `idn-email`, zod uses a custom RegExp which it deems "reasonable".
This is where I wondered if matching `zod.string().email()` to `"format": "email"` actually makes sense, or if we should maybe use `"pattern": "[regex from zod]"` instead. Otherwise one could run into issues where an email is valid for the json schema, but invalid when using zod.

This issue extends to #40, where I'm currently adding RegExps for the aforementioned RFCs - which wouldn't be in line with how zod handles things and leads to enormous patterns being ejected.

I think this deserves a general answer, with options being
1. try to generate a json schema which best contains the information given to the zod schema (use `"format": "idn-email"`)
2. generate a json schema which matches with the validations zod does (use `"pattern": "[regex from zod]"`)

@StefanTerdell

**Comment by StefanTerdell** [comment]
Fair. Check #74

**Comment by marcesengel** [comment]
😍

Lovely! Didn't expect you to directly address this in code to be honest 🚀

**Comment by StefanTerdell** [comment]
Well, I agree with the problem description and it was a fairly quick fix. I'll see about getting it released in the coming days.

**Comment by StefanTerdell** [comment]
Fix released in 3.21.2
