### ISSUE TITLE
additionalProperties should be conditional with zod object strict() not passthrough()

### ISSUE THREAD

**Issue by wwags33** [StefanTerdell/zod-to-json-schema#85]
My objects pass zod parse, but they are failing ajv validation due to additionalProperties being false on all objects the schema.
```ts
const User = z.object({
  name: z.string(),
  company: z.object({
    id: z.string(),
    name: z.string(),
  }),
});
type UserType = z.infer<typeof User>;

const UserJsonSchema = zodToJsonSchema(User, 'User');
const isValidUser = ajv.compile<UserType>(UserJsonSchema);

const userObj = {
  name: 'John Doe',
  company: {
    id: '1234',
    name: 'Acme Corp',
    domain: 'acme.com';
});

User.parse(userObj); // Passes, and strips company.domain.
isValidUser(userObj) // Returns false due to company object schema having additionalProperties: false

```

I would expect the additionalProperties to be false if the zod definition included strict on each object:
```ts
const User = z.object({
  name: z.string(),
  company: z.object({
    id: z.string(),
    name: z.string(),
  }).strict(),
}).strict();
```
In this case, zod parse would match the validation behavior.

Instead I am required to add .passthrough() to all objects in the schema to get similar parse/validate functionality.
```ts
const User = z.object({
  name: z.string(),
  company: z.object({
    id: z.string(),
    name: z.string(),
  }).passthrough(),
}).passthrough();
```

**Comment by StefanTerdell** [comment]
But with the other way around, leaving additionalProperties undefined and passing it through a validator and most parsers would retain the properties instead of stripping them like Zod, so I'm not sure there's a clear answer here

**Comment by StefanTerdell** [comment]
Ive thought about it and it makes sense, but it since it's a breaking change I will probably put it behind an option. Not sure if I have time to put it in the upcoming release though, we'll see

**Comment by gthecht** [comment]
Hi, I wrote a branch with an option to allow this, Its my first time submitting a PR to someone else's repo, so I'm not sure what the correct way to do so is...
