### ISSUE TITLE
[New feature] Add support for example field

### ISSUE THREAD

**Issue by cupcakearmy** [StefanTerdell/zod-to-json-schema#86]
If [this pr](https://github.com/colinhacks/zod/pull/2549) gets merged, the exampe field could be added.

**Comment by StephanMeijer** [comment]
**If** is a big word here :)

**Comment by StefanTerdell** [comment]
Closing for now, doesn't seem to get any traction over at zod

**Comment by dhruvkb** [comment]
Is there a workaround for adding this without it being in Zod (maybe hijacking `.describe` would be a way to getting there)? I am working on some schemas that are pretty confusing and examples would go a long way in clarifying them.

**Comment by punkpeye** [comment]
@dhruvkb have you ever found a workaround?

**Comment by punkpeye** [comment]
I like the idea of jihacking `describe`. Maybe if `describe` has a JSON, those properties are merged with the JSON schema?

**Comment by punkpeye** [comment]
@StefanTerdell is there some way I could hack this together already in the user land?

**Comment by punkpeye** [comment]
Like, adding `transform` or similar option that would be used to finalize conversion to JSON schema per property.

**Comment by StefanTerdell** [comment]
@dhruvkb Check the readme for details on the (new) `postProcess` option :)

**Comment by punkpeye** [comment]
Thank you!!
