### ISSUE TITLE
Represent `Map`s as records

### ISSUE THREAD

**Issue by MOZGIII** [StefanTerdell/zod-to-json-schema#89]
`Map`s are not handled properly. They can't be parsed directly from JSON, so it is not clear how to represent them.
Currently, they are represented as `[K, V][]`, but it would be great to have the ability to use `{ [K]: V }` instead. It matters not that `K` must always be a `string` with this representation, since `zod` has a neat `z.preprocess` feature to fix it before parsing.

**Comment by StefanTerdell** [comment]
> Maps are not handled properly

> it is not clear how to represent them

Pick one :)

It doesn't matter that it has a preprocess if it can't be guaranteed to be used all the time.

**Comment by MOZGIII** [comment]
I ended up using this hack:

```ts
const coercedMap = <K extends ZodTypeAny, V extends ZodTypeAny>(
  keySchema: K,
  valueSchema: V,
) =>
  z.preprocess(
    (arg, ctx) => {
      if (arg === undefined) {
        return new Map();
      }
      const map = new Map(
        Object.entries(arg as {}).map(([key, val]) => [
          keySchema.parse(key, {
            path: [...ctx.path, key, "<key>"],
          }),
          val,
        ]),
      );
      return map;
    }, // scroll down here

    // For JSON Schemas pretend we are an object rather than a map.
    tweaks.jsonSchemaHack
      ? (z.record(keySchema, valueSchema) as never)
      : z.map(keySchema, valueSchema),
  );
```

**Comment by StefanTerdell** [comment]
Sure, wth.

**Comment by StefanTerdell** [comment]
Done in master

**Comment by MOZGIII** [comment]
Sweet! Thanks!
