### ISSUE TITLE
Move zod to peerDependencies

### ISSUE THREAD

**Issue by codetheweb** [StefanTerdell/zod-to-json-schema#9]
Thanks for the great package!

Typescript isn't happy if you list both `zod` and `zod-to-json-schema` in your `package.json` and the resolved versions are slightly off. Would it make sense to move `zod` to `peerDependencies`?

**Comment by StefanTerdell** [comment]
It may! Not sure if there are weird edge cases or something to take into account. Unfortunately I'm super bogged down at work RN so don't have the free time to play around with this myself though.

**Comment by StefanTerdell** [comment]
Basically I'd like to know for sure what we can break by making this change because we can't just up the major.

**Comment by StefanTerdell** [comment]
I looked around on GH and didn't find any projects using this repo and not having zod either as a dependecy or a peerDependency, so I moved Zod to peerDependencies for now. Hope I didn't just ruin someones day lol
