### ISSUE TITLE
Support `readonly()`

### ISSUE THREAD

**Issue by thorhj** [StefanTerdell/zod-to-json-schema#90]
With zod 3.22.0+ we now have [`.readonly()`](https://github.com/colinhacks/zod#readonly) which can be applied to various types, most notably array and object. This is not supported in `zod-to-json-schema` yet, so it just returns an empty schema:

```typescript
import { z } from "zod";
import zodToJsonSchema from "zod-to-json-schema";

const schema = z.object({
  foo: z.boolean(),
  bar: z.number(),
});

console.log("Regular types:");
console.log(zodToJsonSchema(schema));
console.log(zodToJsonSchema(schema.array()));

console.log();
console.log("Readonly types:");
console.log(zodToJsonSchema(schema.readonly()));
console.log(zodToJsonSchema(schema.array().readonly()));

```

```bash
Regular types:
{
  type: 'object',
  properties: { foo: { type: 'boolean' }, bar: { type: 'number' } },
  required: [ 'foo', 'bar' ],
  additionalProperties: false,
  '$schema': 'http://json-schema.org/draft-07/schema#'
}
{
  type: 'array',
  items: {
    type: 'object',
    properties: { foo: [Object], bar: [Object] },
    required: [ 'foo', 'bar' ],
    additionalProperties: false
  },
  '$schema': 'http://json-schema.org/draft-07/schema#'
}

Readonly types:
{ '$schema': 'http://json-schema.org/draft-07/schema#' }
{ '$schema': 'http://json-schema.org/draft-07/schema#' }
```

**Comment by kachkaev** [comment]
Same issue here. Does `readonly()` affect the result or is it a ‘transparent’ definition , like `.catch()`?

https://github.com/StefanTerdell/zod-to-json-schema/blob/b8f2ac75ee19def713af444e9fff42e3817ba3e4/src/parsers/catch.ts#L1-L7

Supporting `.readonly()` should be pretty straightforward in the latter case. Happy to submit a PR if it makes sense.

**Comment by StefanTerdell** [comment]
Done in master

**Comment by fredrikj31** [comment]
When is this gonna be released @StefanTerdell ?

**Comment by StefanTerdell** [comment]
@fredrikj31 about a minute ago

**Comment by kachkaev** [comment]
Great, thanks @StefanTerdell! The new version works like a charm ✨ 

If you have a bit of time, can you please update [the list of releases](https://github.com/StefanTerdell/zod-to-json-schema/releases)?

It should help Renovate (and other similar tools) show the list changes in autogenerated PRs. It is empty at the moment:

![Screenshot 2023-11-18 at 11 58 20](https://github.com/StefanTerdell/zod-to-json-schema/assets/608862/4ce9fe26-a360-44f8-8f39-df4f062c7cea)
