### ISSUE TITLE
Generated regex cannot be used with unicode flag

### ISSUE THREAD

**Issue by rbuetzer** [StefanTerdell/zod-to-json-schema#93]
It appears to me that the regex patterns generated by `zodToJsonSchema` cannot always handle the regex [unicode flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions#advanced_searching_with_flags).

### Steps to reproduce

Run the follwoing code ([Example on StackBlitz](https://stackblitz.com/edit/js-oymqny?file=index.js))

```js
const zodSchema = z.string().includes("@");
const jsonSchema = zodToJsonSchema(zodSchema);

const regex = new RegExp(jsonSchema.pattern, 'u');
```

### Observed behavior

- A runtime error `invalid identity escape in regular expression` is thrown in the last line
- If `new RegExp(…)` is called without the `u` flag, no error is thrown

### Expected behavior

No runtime error is thrown

### Analysis

The generated JSON schema looks like this:

```json
{
  "type": "string",
  "pattern": "\\@",
  "$schema": "http://json-schema.org/draft-07/schema#"
}
```

The problem is, that the `@` is escaped.

The [MDN docs on `\`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet) state:

> Escape sequences like \:, \-, \@ will be equivalent to their literal, unescaped character equivalents in regular expressions. However, in regular expressions with the [unicode flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions#advanced_searching_with_flags), these will cause an invalid identity escape error.

**Comment by StefanTerdell** [comment]
JFC I hate regex

Would adding an option to not escape special characters be a solution?

**Comment by StefanTerdell** [comment]
Try the new patternStrategy option if you run into this.
