### ISSUE TITLE
Incorrect $ref for self-referencing types

### ISSUE THREAD

**Issue by LaserUnicorns** [StefanTerdell/zod-to-json-schema#99]
Given a self-referencing type:
```ts
const Test = z.lazy(() =>
  z.object({
    id: z.string(),
    test: z.optional(Test),
  }),
)
```

When using zodToJsonSchema, the produced JSON schema is as follows:
```jsonc
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "test": {
      "$ref": "#/" // <- this one
    }
  },
  "required": [
    "id"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#"
}
```

The issue arises with the "$ref" property under "test," which currently contains `#/`. According to [RFC6901](https://datatracker.ietf.org/doc/html/rfc6901#section-6), this points to an empty string property:
```json
{
  "": "this"
}
```

To adhere to the RFC, the $ref property should simply contain `#`, pointing to the entire document.

**Comment by StefanTerdell** [comment]
Fair. Fix published in 3.22.3
